# Generated by Django 4.2.2 on 2023-06-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_task_image_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_image',
            field=models.ImageField(upload_to='task_image'),
        ),
    ]
