# Generated by Django 4.2.2 on 2023-06-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
